sudo: required
services:
  - docker
language: go
script:
  - go build -o fib
deploy:
  provider: script
  skip_cleanup: true
  script: curl -sL https://git.io/goreleaser | bash
  on:
    branch: master
